on:
  push:
    branches:
      - master
jobs:
  client:
    name: deploy to staging
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
      - name: steup node
        uses: actions/setup-node@v4
        with:
          node-version: '10.x'
        
      - name: install dependencies
        run: npm install

      - name: move dist to tencent server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          username: ${{ secrets.TENCENT_USER_NAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}
          port: 22
          source: ./client/dist
          target: /root/store/new-navigator

    
          
